### get userlist
GET http://127.0.0.1:8000/api/userlist
Content-Type: application/json
Authorization: Bearer 10|u4rC39ozBOI8XoQI62uWeRzS1JTm04uuUqnyXOe2e1537dc0

### signup
POST http://127.0.0.1:8000/api/signup
Content-Type: application/json

{
  "name": "Gyane",
  "email": "gyanee1@test.com",
  "password": "abc1234"
}

### Login
POST http://127.0.0.1:8000/api/login
Content-Type: application/json
Authorization: Bearer 10|u4rC39ozBOI8XoQI62uWeRzS1JTm04uuUqnyXOe2e1537dc0

{
  
   "email": "gyanee1@test.com",
  "password": "abc1234"
}